name: multi_vendor_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  google_fonts: ^6.2.1
  animate_do: ^3.3.7
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Ensures that Material Icons font is included in your app.
  uses-material-design: true

  # Assets included in the application.
  assets:
    - assets/icon.webp
    - assets/banner.jpeg
    - assets/banner2.jpg
    - assets/banner5.jpg
    - assets/banner3.webp
    - assets/banner6.jpeg
    - assets/banner4.jpeg
    - assets/mainicon.png

  # Uncomment and configure fonts below if needed.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_launcher_icons:
  android: "launcher_icon"          # Generates Android launcher icons
  ios: true                         # Generates iOS launcher icons
  remove_alpha_ios: true            # Removes transparency for iOS icons (important for Apple App Store)
  image_path: "assets/mainicon.png"  # Path to your main icon file
  min_sdk_android: 24               # Minimum Android SDK version
  adaptive_icon_background: "#00000000"   # Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/mainicon.png"  # Foreground icon for Android adaptive icons

